// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthRepoMock is an autogenerated mock type for the IrepoAuth type
type AuthRepoMock struct {
	mock.Mock
}

// SelectUserByEmail provides a mock function with given fields: email
func (_m *AuthRepoMock) SelectUserByEmail(email string) (error, int) {
	ret := _m.Called(email)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string) int); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthRepoMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthRepoMock creates a new instance of AuthRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthRepoMock(t mockConstructorTestingTNewAuthRepoMock) *AuthRepoMock {
	mock := &AuthRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
