// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "e-commerce/domains/category/entity"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the IrepoCategory type
type CategoryRepository struct {
	mock.Mock
}

// GetCategory provides a mock function with given fields:
func (_m *CategoryRepository) GetCategory() ([]entity.CategoryEntity, error) {
	ret := _m.Called()

	var r0 []entity.CategoryEntity
	if rf, ok := ret.Get(0).(func() []entity.CategoryEntity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CategoryEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCategoryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryRepository(t mockConstructorTestingTNewCategoryRepository) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
