// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	users "e-commerce/domains/users/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the IuserInterface type
type UserRepository struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: dataDelete
func (_m *UserRepository) DeleteUser(dataDelete users.Users) (int, error) {
	ret := _m.Called(dataDelete)

	var r0 int
	if rf, ok := ret.Get(0).(func(users.Users) int); ok {
		r0 = rf(dataDelete)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Users) error); ok {
		r1 = rf(dataDelete)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectUser provides a mock function with given fields:
func (_m *UserRepository) SelectUser() ([]users.Users, error) {
	ret := _m.Called()

	var r0 []users.Users
	if rf, ok := ret.Get(0).(func() []users.Users); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Users)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: dataUpdate
func (_m *UserRepository) UpdateUser(dataUpdate users.Users) (int, error) {
	ret := _m.Called(dataUpdate)

	var r0 int
	if rf, ok := ret.Get(0).(func(users.Users) int); ok {
		r0 = rf(dataUpdate)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Users) error); ok {
		r1 = rf(dataUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
